# SPDX-License-Identifier: CC0-1.0
#
# Cargo.toml
#
# This file is a component of ShadyURL by Elizabeth Myers.
#
# To the extent possible under law, the person who associated CC0 with
# ShadyURL has waived all copyright and related or neighboring rights
# to ShadyURL.
#
# You should have received a copy of the CC0 legalcode along with this
# work.  If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.

[package]
name = "shadyurl-rust"
version = "0.1.0"
edition = "2021"
rust-version = "1.65.0"
authors = ["Elizabeth Myers"]
description = "A webapp that makes URLs shady"
license = "CC0-1.0"
homepage = "https://github.com/Elizafox/ShadyURL-Rust"
repository = "https://github.com/Elizafox/ShadyURL-Rust"
readme = "README.md"

[workspace]
members = [".", "entity", "migration"]

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true

[dependencies]
entity = { path = "entity" }
migration = { path = "migration" }

anyhow = { version = "1.0.71", features = ["backtrace"] }
argon2-kdf = "1.1.2"
askama = { version = "0.12.0", features = ["with-axum"] }
askama_axum = { version = "0.3.0", features = ["config", "humansize"] }
async-fred-session = "0.1.4"
axum = { version = "0.6.18", features = ["macros", "http2", "headers", "multipart", "tracing"] }
axum_csrf = "0.6.2"
axum-login = "0.5.0"
dotenvy = "0.15.7"
itertools = "0.11.0"
lazy_static = "1.4.0"
log = { version = "0.4.19", features = ["std"] }
nix = "0.26.2"
num_cpus = "1.16.0"
os_str_bytes = "6.5.1"
rand = "0.8.5"
sea-orm = { version = "0.11.3", features = ["sqlx-all", "runtime-tokio-native-tls", "macros", "with-chrono"] }
sea-query = { version = "0.28.5", features = ["with-chrono", "thread-safe"] }
serde = { version = "1.0.171", features = ["derive"] }
syslog-tracing = "0.2.0"
tokio = { version = "1.29.1", features = ["fs", "macros", "net", "parking_lot", "rt-multi-thread", "signal", "time", "tracing"] }
tower = { version = "0.4.13", features = ["timeout", "tokio"] }
tower-http = { version = "0.4.1", features = ["async-compression", "compression-full", "decompression-full", "fs", "trace", "timeout", "tokio", "tower", "tracing"] }
tower_governor = { version = "0.0.4", features = ["tracing"] }
tracing = { version = "0.1.37", features = ["async-await", "log"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "parking_lot", "serde", "time", "tracing", "tracing-serde"] }
url = "2.4.0"
validator = { version = "0.16.1", features = ["derive"] }
