# SPDX-License-Identifier: CC0-1.0
#
# Cargo.toml
#
# This file is a component of ShadyURL by Elizabeth Myers.
#
# To the extent possible under law, the person who associated CC0 with
# ShadyURL has waived all copyright and related or neighboring rights
# to ShadyURL.
#
# You should have received a copy of the CC0 legalcode along with this
# work.  If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.

[package]
name = "shadyurl-rust"
version = "0.1.0"
edition = "2021"
rust-version = "1.65.0"
authors = ["Elizabeth Myers"]
description = "A webapp that makes URLs shady"
license = "CC0-1.0"
homepage = "https://github.com/Elizafox/ShadyURL-Rust"
repository = "https://github.com/Elizafox/ShadyURL-Rust"
readme = "README.md"

[workspace]
members = [".", "entity", "migration"]

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true

[features]
default = ["sqlite"]
mysql = ["sea-orm/sqlx-mysql", "migration/mysql"]
postgres = ["sea-orm/sqlx-postgres", "migration/postgres"]
sqlite = ["sea-orm/sqlx-sqlite", "migration/sqlite"]
with-tracing = ["axum/tracing", "tokio/tracing", "tower/tracing", "tower-http/tracing"]

[dependencies]
entity = { path = "entity" }
migration = { path = "migration" }


######################################
# Package dependencies go below here #
######################################

anyhow = { version = "1.0.72", features = ["backtrace"] }
argon2-kdf = "1.2.0"
askama = { version = "0.12.0", features = ["with-axum"] }
askama_axum = { version = "0.3.0", features = ["config", "humansize"] }
async-fred-session = "0.1.5"
axum = { version = "0.6.19", features = ["macros", "http2", "headers"] }
axum-client-ip = "0.4.1"
axum_csrf = { version = "0.7.2", features = ["layer"] }
axum-login = "0.5.0"
dotenvy = "0.15.7"
envy = "0.4.2"
rand_chacha = { version = "0.3.1", features = ["simd"] }
itertools = "0.11.0"
lazy_static = "1.4.0"
log = { version = "0.4.19", features = ["std"] }
nix = "0.26.2"
num_cpus = "1.16.0"
once_cell = { version = "1.18.0", features = ["parking_lot"] }
os_str_bytes = "6.5.1"
proctitle = "0.1.1"
rand = "0.8.5"
rand_distr = "0.4.3"
sea-orm = { version = "0.11.3", features = ["macros", "runtime-tokio-native-tls", "with-chrono"] }
sea-query = { version = "0.30.0", features = ["thread-safe", "with-chrono"] }
serde = { version = "1.0.174", features = ["derive"] }
serde_bytes = "0.11.12"
syslog-tracing = "0.2.0"
tokio = { version = "1.29.1", features = ["fs", "macros", "parking_lot", "rt-multi-thread", "signal", "time"] }
tracing = { version = "0.1.37", features = ["async-await", "log"]}
tracing-subscriber = { version = "0.3.17", features = ["parking_lot"]}
tower = { version = "0.4.13", features = ["timeout", "tokio"] }
tower-http = { version = "0.4.3", features = ["fs", "timeout", "tokio", "tower"] }
url = "2.4.0"
validator = { version = "0.16.1", features = ["derive"] }
