/* SPDX-License-Identifier: CC0-1.0
 *
 * entity/src/entities/prelude.rs
 *
 * This file is a component of ShadyURL by Elizabeth Myers.
 *
 * To the extent possible under law, the person who associated CC0 with
 * ShadyURL has waived all copyright and related or neighboring rights
 * to ShadyURL.
 *
 * You should have received a copy of the CC0 legalcode along with this
 * work.  If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
 */

//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::url::Entity as Url;
