/* SPDX-License-Identifier: CC0-1.0
 *
 * src/generate.rs
 *
 * This file is a component of ShadyURL by Elizabeth Myers.
 *
 * To the extent possible under law, the person who associated CC0 with
 * ShadyURL has waived all copyright and related or neighboring rights
 * to ShadyURL.
 *
 * You should have received a copy of the CC0 legalcode along with this
 * work.  If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
 */

use std::collections::HashSet;

use once_cell::sync::Lazy;
use rand::{
    distributions::{Distribution, Uniform},
    prelude::*,
};

use crate::util::macros::arr;

#[derive(PartialEq, Eq, Copy, Clone)]
enum Mangler {
    NoOp,
    RandomUppercase,
    AllUppercase,
    ReplaceSeps,
}

fn generate_hash(rng: &mut dyn RngCore) -> String {
    arr!(const CHARS: [u8; _] = *b"abcdefghijiklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_+$");
    let distr_chars = Lazy::new(|| Uniform::new(0, CHARS.len()));
    let distr_count = Lazy::new(|| Uniform::new_inclusive(8, 16));

    let char_count = distr_count.sample(rng);
    (0..char_count)
        .map(|_| CHARS[distr_chars.sample(rng)] as char)
        .collect()
}

fn perform_mangle(fragment: &str, mangler: Mangler, rng: &mut dyn RngCore) -> String {
    match mangler {
        Mangler::RandomUppercase => fragment
            .chars()
            .map(|ch| {
                let distr_cap = Lazy::new(|| Uniform::new(0, 3));
                if (*distr_cap).sample(rng) == 0 {
                    // This is safe; we don't have unicode chars.
                    ch.to_uppercase().next().unwrap()
                } else {
                    ch
                }
            })
            .collect(),
        Mangler::AllUppercase => fragment.to_uppercase(),
        Mangler::ReplaceSeps => fragment
            .chars()
            .map(|ch| {
                let distr_replace = Lazy::new(|| Uniform::new(0, 4));
                if ch == '-' && (*distr_replace).sample(rng) == 0 {
                    const SEPS: &[u8] = b"!_+$";
                    let distr_seps = Lazy::new(|| Uniform::new(0, SEPS.len()));
                    SEPS[(*distr_seps).sample(rng)] as char
                } else {
                    ch
                }
            })
            .collect(),
        Mangler::NoOp => fragment.to_string(),
    }
}

fn get_mangler(rng: &mut dyn RngCore) -> Mangler {
    let distr_one_fourth = Lazy::new(|| Uniform::new(0, 12));
    match (*distr_one_fourth).sample(rng) {
        // 1/4 probability of selecting a mangler
        0 => Mangler::AllUppercase,
        1 => Mangler::RandomUppercase,
        2 => Mangler::ReplaceSeps,
        _ => Mangler::NoOp,
    }
}

fn mangle_fragment(fragment: &str, rng: &mut dyn RngCore) -> String {
    // Select mangling function
    let mangler = get_mangler(rng);
    let new = perform_mangle(fragment, mangler, rng);

    if rng.gen() && mangler != Mangler::NoOp {
        if mangler == Mangler::AllUppercase || mangler == Mangler::RandomUppercase {
            // Don't repeat a case mangling
            return perform_mangle(&new, Mangler::ReplaceSeps, rng);
        } else if mangler == Mangler::ReplaceSeps {
            let mangler = if rng.gen() {
                Mangler::AllUppercase
            } else {
                Mangler::RandomUppercase
            };
            return perform_mangle(&new, mangler, rng);
        }
    }

    new
}

pub(crate) fn shady_filename(rng: &mut dyn RngCore) -> String {
    arr!(const SEPS: [&str; _] = ["-", "!", "_", "+", "$"]);

    // These never change, so no point in regenerating them each time
    let distr_seps = Lazy::new(|| Uniform::new(0, SEPS.len()));
    let distr_nsfw = Lazy::new(|| Uniform::new(0, NSFW.len()));
    let distr_ext = Lazy::new(|| Uniform::new(0, EXT.len()));
    let distr_count = Lazy::new(|| Uniform::new_inclusive(6, 12));

    let hash = generate_hash(rng);

    /* We multiply by 2 so we can put on the separators and suffix
     * The total number of separators plus the suffix works out to be double the nsfw_count.
     * This means the hash_pos must be doubled, too, to be in the right spot.
     */
    let nsfw_count = distr_count.sample(rng) * 2;
    let hash_pos = rng.gen_range(0..nsfw_count) * 2;

    let mut seen_set = HashSet::new();
    (0..nsfw_count)
        .map(|i| {
            if (i & 1) == 1 {
                // This is odd. Do we tack on the suffix or a separator?
                if i == nsfw_count - 1 {
                    EXT[(*distr_ext).sample(rng)].to_string()
                } else {
                    // This position will always be odd, since nsfw_count * 2 is always even.
                    // NB: the range is [0..nsfw_count * 2)
                    //
                    SEPS[(*distr_seps).sample(rng)].to_string()
                }
            } else if i == hash_pos {
                hash.clone()
            } else {
                // Loop until we get a unique NSFW fragment
                loop {
                    let pos = (*distr_nsfw).sample(rng);
                    if seen_set.contains(&pos) {
                        continue;
                    }
                    seen_set.insert(pos);
                    return mangle_fragment(NSFW[pos], rng);
                }
            }
        })
        .collect()
}

arr!(const NSFW: [&str; _] = [
    "0-percent-artificial",
    "0-percent-risk",
    "1-dollar-iphone",
    "100-percent-legal",
    "100-percent-natural",
    "1man1jar",
    "2girls1cup",
    "2guys1horse",
    "3girlsfingerpaint",
    "3guys1hammer",
    "419-scam",
    "420",
    "500-dollar-cash-prize",
    "69",
    "7-11-robbery",
    "800-dollars-4u",
    "911-call",
    "9-11-jumper",
    "9-11-video",
    "abuse",
    "adblock-bypass",
    "admin",
    "ads",
    "advert",
    "affair",
    "al-qaeda",
    "al-qaeda-signup",
    "alien-abduction",
    "all-natural",
    "ambien",
    "america",
    "anal",
    "anal-penetration",
    "anal-sex",
    "anarchy",
    "ancient-cure",
    "ancient-diet-pills",
    "anti-aging-pills",
    "anti-e-pills",
    "anti-estrogen-pills",
    "anti-t-pills",
    "anti-testosterone-pills",
    "antifa-kills-maga",
    "antifamurder",
    "antivirus",
    "apple-giveaway",
    "arpa",
    "ass",
    "ass2ass",
    "assfucking",
    "ass2mouth",
    "ass-beating",
    "assault",
    "audio",
    "babes",
    "back-orifice",
    "backdoor",
    "bad-mixtape",
    "badonkadonk",
    "bang",
    "bang-women",
    "bank-transfer",
    "barely-legal",
    "bargains",
    "basic",
    "bbw",
    "bdsm",
    "beatdown",
    "beatingwomen",
    "beheading",
    "betting",
    "bigbang",
    "bigcashprize",
    "bigcocks",
    "bigmilf",
    "bigwillie",
    "bigwomen",
    "billionaire",
    "bitcoin-2x",
    "bitcoin-billionaire",
    "bitcoin-cash-paydirt",
    "bitcoin-miner",
    "bitcoin-multiplier",
    "blackmaildox",
    "blood",
    "bloody-murder",
    "bodies",
    "body",
    "bodybuilders",
    "bomb",
    "bombing",
    "bondage",
    "bot",
    "boyfriendcamera",
    "boyfriendphone",
    "boyfriendtracker",
    "bribe-your-boss-legally",
    "build-muscle",
    "bupropion",
    "butt",
    "buttsex",
    "bypass",
    "calcium",
    "cash",
    "cash-money",
    "casino",
    "casino-loosest-slots",
    "cat-torture",
    "celeb-addresses",
    "celeb-phone-numbers",
    "celeb-sextape",
    "chat",
    "chat-with-babes",
    "cheap",
    "cheap-guns-ammo",
    "cheapcialis",
    "cheapdrugs",
    "cheappills",
    "cheapviagra",
    "cheat",
    "cheat-at-casino-legally",
    "cheating",
    "chop",
    "christian",
    "christian-evangelism",
    "christian-murder",
    "chromium-supplement",
    "cialis",
    "classified",
    "classified-doxxx",
    "click",
    "click-here",
    "clone-phone",
    "clone-simcard",
    "clownpenis",
    "cobalt-supplement",
    "cocaine",
    "cock",
    "cockfights",
    "coin",
    "coin-multiplier",
    "conspiracy",
    "cookie",
    "cookiestealer",
    "coupon",
    "cowgirl",
    "crack",
    "craigslist-blowjob",
    "craigslist-hookup",
    "creditcard",
    "creditcard-numbers",
    "crime-tips",
    "crypto",
    "cummy",
    "cure",
    "cure-anything",
    "cyber",
    "cyber-attack",
    "cyberstalk",
    "daesh",
    "daesh-meetup",
    "daesh-recruitment",
    "daesh-signup",
    "darkweb",
    "date-hot-babes",
    "date-hot-chix",
    "date-hot-guys",
    "date-hot-trans-babes",
    "date-hot-trans-chix",
    "date-hot-trans-guys",
    "dating-4-old-ppl",
    "dead-animals",
    "dead-people",
    "deals",
    "death",
    "declassified",
    "declassified-dox",
    "deepfake",
    "deepweb",
    "deepweb-drugs",
    "deepweb-guns",
    "deploy",
    "detector",
    "diaper-kink",
    "diazepam",
    "dick",
    "dick-enlargement",
    "diet",
    "diet-fast-weight-loss",
    "diet-supplement",
    "digital",
    "digital-currency",
    "digital-pharmacy",
    "dildo",
    "dns",
    "doctor",
    "doctor-recommended",
    "dog-sex",
    "dog-torture",
    "dollar",
    "dollar-forex",
    "domestic-abuse",
    "donate",
    "donkey-cock",
    "donkey-show",
    "dothisbytomorrow",
    "dothisnow",
    "doxxing",
    "doxxx",
    "drive-by-shooting",
    "drugs",
    "dungeon",
    "earn-ur-degree-online",
    "easy-men",
    "easy-money",
    "easy-women",
    "echinacea",
    "effexor",
    "election-fraud",
    "email",
    "email-scam",
    "endless-health",
    "endless-money",
    "enhancement",
    "escort",
    "estradiol",
    "estrogen",
    "etherium",
    "etherium-multiplier",
    "euro",
    "euro-forex",
    "evangelical",
    "evidence",
    "exclusive-sex-tape",
    "exe",
    "execute",
    "extra",
    "fake",
    "fakelogin",
    "famine",
    "fap",
    "fappening",
    "fast",
    "fast-remedy",
    "fast-weight-loss",
    "fight-aging",
    "finalsolution",
    "final-moments",
    "final-opportunity",
    "finder",
    "fingering",
    "fisting",
    "flash",
    "flightpoints",
    "forex",
    "forex-interbank",
    "forex-no-bear-market",
    "footage-of-death",
    "footfetish",
    "foot-porn",
    "fraud",
    "freakout",
    "free",
    "free-android",
    "free-internet",
    "free-iphone",
    "free-meds",
    "free-phone",
    "free-pills",
    "free-porn",
    "free-shows",
    "free-tv",
    "free-virus-removal",
    "free-webcams",
    "french",
    "frottage",
    "fuck",
    "gangbang",
    "gay",
    "gay-sex",
    "german",
    "german-scat-porn",
    "get-a-girl",
    "get-jacked",
    "get-laid-tonite",
    "get-rich-overnight",
    "get-rich-quick",
    "getting-fucked",
    "ghetto",
    "ginger",
    "girl",
    "girlcock",
    "girldick",
    "girlfriend",
    "girlfriend-camera",
    "girlfriend-phone",
    "girlfriendtracker",
    "giveaway",
    "gmail",
    "goatse",
    "gone-wild",
    "gone-wrong",
    "google",
    "gore",
    "government-documents",
    "government-dox",
    "gps",
    "gps-location",
    "gps-track",
    "grindr",
    "gun-fight",
    "guns",
    "hacker",
    "hateminorities",
    "he-dies",
    "he-fux-her",
    "headshot",
    "helicopter-crash",
    "herbal",
    "herbal-remedy",
    "heroin",
    "hidden",
    "hijack",
    "hijacker",
    "hitler",
    "hitler-sex-film",
    "holistic-medicine",
    "homeless-death",
    "homeless-man-murder",
    "homeless-woman-murder",
    "homeopathic",
    "hood-shooting",
    "horny-goat-weed",
    "horny-teens",
    "horny-women",
    "horse-sex",
    "hot-babes",
    "hot-goats",
    "hot-women",
    "hotmail",
    "how-2-win-at-casino",
    "how-to-win",
    "huge-cash-prize",
    "huge-cocks",
    "hypnosis",
    "i-love-u",
    "i-make-2000-week-at-home",
    "i-was-abducted-by-aliens",
    "i-was-probed",
    "ied",
    "illegal",
    "illegal-drugs",
    "illegal-guns-4-sale",
    "illegal-porno",
    "impersonate",
    "increase-ur-e",
    "increase-ur-t",
    "india",
    "install",
    "internet",
    "interview",
    "intifada",
    "invis",
    "ip-finder",
    "ip-hijacker",
    "ip-stealer",
    "iron",
    "irs",
    "isis",
    "isis-recruiter",
    "isis-training-camp",
    "islam",
    "islam-murder",
    "israel",
    "jacked-off",
    "jacking",
    "jacking-it",
    "jacking-off",
    "jackpot",
    "jackpot-lottry-winner",
    "jail-beatdown",
    "jail-murder",
    "jail-stabbing",
    "jailbait",
    "jailbreak",
    "jailhouse-beatdown",
    "jailhouse-murder",
    "jailhouse-stabbing",
    "japan",
    "japanese",
    "japanese-tentacle-porn",
    "jar-inserted",
    "jar-jar-porn",
    "java",
    "javascript",
    "javascript-exploit",
    "jelqing",
    "jew-nwo",
    "jewish-conspiracy",
    "jewishbanks",
    "jihad",
    "jizz",
    "jizz-fountain",
    "join-an-orgy",
    "join-now",
    "join-our-cult",
    "join-our-religion",
    "join-us",
    "joinisis",
    "journalist",
    "k9",
    "keygen",
    "keylog",
    "keylogger",
    "kill",
    "kill-all-immigrants",
    "killgays",
    "killing",
    "killwomen",
    "king",
    "king-scandal",
    "kinky",
    "kitty",
    "knife-fight",
    "krack",
    "krazy-deals",
    "krazy-good-deal",
    "launch",
    "leak",
    "leaked-documents",
    "leaked-dox",
    "legal",
    "legend-jackpot",
    "legend-tits",
    "legendary-growth",
    "lemonparty",
    "lesbian",
    "lesbians-fuck",
    "lesbo",
    "levitra",
    "lexapro",
    "lezbo",
    "linux",
    "local",
    "local-men",
    "local-women",
    "locator",
    "loli",
    "lolicon",
    "lonely-women",
    "loose-slots",
    "loose-sluts",
    "lorazepam",
    "lotto-winner",
    "lsd",
    "m4m",
    "m4t",
    "m4w",
    "macos",
    "maga",
    "magic",
    "magic-cure",
    "magic-mushrooms",
    "magic-weight-loss",
    "make-her-cum",
    "make-money-at-home",
    "make-money-doing-nothing",
    "make-money-fast",
    "male-enhancement",
    "malicious",
    "malware",
    "many-babes",
    "marijuana",
    "mature",
    "mdma",
    "medical",
    "medical-magic-mushrooms",
    "medical-mmj",
    "medical-mushrooms",
    "meds",
    "meds-4-cheap",
    "meds-from-canada",
    "meds-from-europe",
    "meds-from-vanuatu",
    "mega",
    "mega-jackpot",
    "mega-tits",
    "mein-kampf",
    "mercenary",
    "microsoft-giveaway",
    "mike-pence",
    "mike-pence-gay",
    "mike-pence-naked",
    "milf",
    "milf-tits",
    "millionaire",
    "mine-coins-for-free",
    "mom-daughter-fuck",
    "mom-has-sex-with-son",
    "mommy-milkers",
    "monster-erection",
    "more-cash",
    "more-income",
    "more-money",
    "more-wins",
    "msm-supplement",
    "multivitamin",
    "mushrooms",
    "muslim",
    "muslim-murders-christian",
    "my-tits-are-legend",
    "naked",
    "naked-celebs",
    "nazi",
    "nazi-beatdown",
    "new",
    "new-cure",
    "new-drugs",
    "new-income",
    "new-remedy",
    "new-world-order",
    "nft",
    "nigeria-bank-transfer",
    "no-risk",
    "nsfw",
    "nudes",
    "nwo",
    "old-ladies",
    "old-man-gangbang",
    "old-men",
    "old-remedy",
    "onlinebetting",
    "onlinepharma",
    "online-horse-race",
    "online-pharmacy",
    "only-10-dollars",
    "orangutansex",
    "organ",
    "organ-selling",
    "overnight",
    "overnight-cure",
    "overnight-growth",
    "overnight-wealth",
    "overnight-weight-loss",
    "overnite-billionaire",
    "overnite-millionaire",
    "overnite-success",
    "overnite-trillionaire",
    "paranomal",
    "password",
    "penetration",
    "penis-enlargement",
    "petit-milf",
    "pewdiepie-sextape",
    "pharma",
    "pharma-canada",
    "pharma-euro",
    "pharma-vanuatu",
    "pharmacy",
    "phishing",
    "phone",
    "phone-numbers",
    "phosphorous-supplements",
    "physical-removal",
    "pickup",
    "pickup-girls",
    "pigsex",
    "pills",
    "pills4cheap",
    "pimp",
    "pipebomb",
    "pirated-movies",
    "pirated-music",
    "pirated-podcasts",
    "pirated-shows",
    "pizzagate",
    "poker",
    "poker-real-money",
    "police-bodycam",
    "poop",
    "popunder",
    "popup",
    "porn",
    "prince",
    "prince-scandal",
    "princess",
    "princess-scandal",
    "probe",
    "probing",
    "protein",
    "protein-powder",
    "prozac",
    "psilocybin",
    "psilocybin-online",
    "public",
    "public-sex",
    "pussy",
    "pussy-fuck",
    "putin",
    "putin-naked",
    "putins-dick",
    "pwn",
    "qanon",
    "qanon-reveal",
    "queen",
    "queen-nudes",
    "queen-scandal",
    "quickie",
    "quickly-get-rich",
    "quit-ur-job",
    "racist",
    "racket",
    "rapid-growth",
    "rapid-weightloss",
    "rat-sex",
    "read",
    "real",
    "real-catsex",
    "real-death",
    "real-dogsex",
    "real-donkeyshow",
    "really-horny-girls",
    "remedy",
    "remote",
    "remote-viewing",
    "remove-virus",
    "reverse",
    "rich",
    "rich-overnight",
    "rickroll",
    "ripoff",
    "ripped-fast",
    "risperidol",
    "root",
    "rootkit",
    "rope-bondage",
    "rope-porn",
    "russia",
    "russian",
    "russian-bots",
    "russian-brides",
    "scam",
    "scandal",
    "scat",
    "scat-porn",
    "school-shooting",
    "scissoring",
    "secret",
    "secret-plans",
    "secretary",
    "see-her-webcam",
    "see-my-pussy",
    "see-my-tits",
    "sell-your-organs",
    "seroquel",
    "sex",
    "sex-offender",
    "sex-tape",
    "sext",
    "sexting",
    "sexwithcats",
    "sexwithdogs",
    "sexwithgerbils",
    "sexy",
    "sexy-ladies",
    "sexy-women",
    "shartporn",
    "she-fux-him",
    "she-will-never-know",
    "shedies",
    "shemale",
    "shes-barely-legal",
    "sheswaiting4u",
    "shit",
    "shit-fucking",
    "shitfountain",
    "shocking",
    "shocksite",
    "shooting",
    "shoplifting",
    "shota",
    "shotacon",
    "sim-clone",
    "skinned-alive",
    "skinned-cats",
    "slutcams",
    "sluts",
    "smallcocks",
    "sms",
    "snuff-films",
    "social-security",
    "sound",
    "source-code",
    "source-code-leak",
    "spam",
    "spy",
    "spy-on-ur-boyfriend",
    "spy-on-ur-girlfriend",
    "spy-on-ur-husband",
    "spy-on-ur-wife",
    "spyware",
    "st-johns-wort",
    "stalk-her",
    "steal",
    "stoned",
    "stoned-for-adultery",
    "stud",
    "stuxnet",
    "subway-death",
    "supplements",
    "supplements-cheap",
    "suppository",
    "swissporn",
    "swiss-bank-account",
    "swiss-lotto-winner",
    "t4m",
    "t4t",
    "t4w",
    "takeover",
    "taliban-interview",
    "taliban-meetup",
    "taliban-recruiter",
    "teen",
    "teen-barely-legal",
    "telegram",
    "televangelist",
    "terrorist",
    "testosterone",
    "testosterone-supplement",
    "the-donald",
    "the-truth-about-jews",
    "thetruth",
    "they-hurt-her",
    "theycantstopyou",
    "theyhatethis",
    "threesomes",
    "threesomes-near-u",
    "tighten-my-pussy",
    "tokens",
    "toosexy",
    "toosexy4youtube",
    "toohotfortv",
    "tool",
    "tor",
    "torrent",
    "torrent-anything",
    "track-my-ex",
    "track-my-wife",
    "tracker",
    "trans",
    "trans-agenda",
    "trans-doctor",
    "trans-porn",
    "trillionaire",
    "trojan",
    "turkey-porn",
    "twitter-blowjob",
    "un-nwo-conspiracy",
    "underground-death",
    "unlocker",
    "ur-hubby-is-cumming",
    "ur-jackpot-awaits",
    "ur-wife-is-cumming",
    "usa",
    "vagina",
    "vaginal-rejeuvenation",
    "vanadium-supplement",
    "viagra",
    "video",
    "virus",
    "vitamin-b12",
    "vitamin-b6",
    "vitamin-c",
    "vitamin-d",
    "vitamin-e",
    "vitamins",
    "vpn",
    "vuln",
    "vulns",
    "w4m",
    "w4t",
    "w4w",
    "war-crimes",
    "war-photos",
    "warez",
    "watch",
    "watch-her-die",
    "watch-her-get-fukd",
    "watch-her-webcam",
    "watch-him-die",
    "watch-movies-4-free",
    "watch-tv-for-free",
    "web",
    "weed",
    "weightloss",
    "wet",
    "wet-fart-porn",
    "wet-pussy",
    "wfh",
    "what-hes-doing",
    "what-shes-doing",
    "what-they-dont-want-u2-know",
    "whitepower",
    "whos-my-husband-txting",
    "whos-my-wife-been-txting",
    "wifepussy",
    "win",
    "winatblackjack",
    "winatpoker",
    "winbig",
    "windows",
    "winning",
    "winning-lotto-numbers",
    "womanbeaten",
    "woman-gets-stoned",
    "women",
    "work-at-home",
    "worldstar",
    "worldstarfight",
    "worm",
    "wow",
    "xtc",
    "xxx",
    "xxx-pussy",
    "xxx-tits",
    "xxxtra",
    "yahoo",
    "yen",
    "yenforex",
    "your-ip",
    "your-ssn",
    "youtube-download",
    "zinc-supplement",
    "zoo",
    "zooporn",
    "zoom",
]);

arr!(const EXT: [&str; _] = [
    ".app", ".avi", ".bas", ".bat", ".csv", ".divx", ".dll", ".doc", ".docx", ".exe", ".flv", ".gif", ".htm",
    ".html", ".hxt", ".ini", ".jar", ".js", ".jpeg", ".jpg", ".m1v", ".m4a", ".mid", ".midi", ".mkv", ".mod",
    ".mov", ".movie", ".mpa", ".mpe", ".mpeg", ".mpg", ".mp3", ".mp4", ".msi", ".p7r", ".pdf", ".png", ".ppt",
    ".pptx", ".rar", ".sgml", ".snd", ".swf", ".tiff", ".txt", ".webm", ".webp", ".vbs", ".xaf", ".xhtml",
    ".xls", ".xlsx", ".xml", ".zip",
]);
