/* SPDX-License-Identifier: CC0-1.0
 *
 * src/generate.rs
 *
 * This file is a component of ShadyURL by Elizabeth Myers.
 *
 * To the extent possible under law, the person who associated CC0 with
 * ShadyURL has waived all copyright and related or neighboring rights
 * to ShadyURL.
 *
 * You should have received a copy of the CC0 legalcode along with this
 * work.  If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
 */

use std::collections::HashSet;

use once_cell::sync::Lazy;
use rand::{
    distributions::{Distribution, Uniform},
    prelude::*,
};

use crate::util::macros::arr;

#[derive(PartialEq, Eq, Copy, Clone)]
enum Mangler {
    NoOp,
    RandomUppercase,
    AllUppercase,
    ReplaceSeps,
}

fn generate_hash(rng: &mut dyn RngCore) -> String {
    arr!(const CHARS: [u8; _] = *b"abcdefghijiklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_+$");
    let distr_chars = Lazy::new(|| Uniform::new(0, CHARS.len()));
    let distr_count = Lazy::new(|| Uniform::new_inclusive(5, 12));

    let char_count = distr_count.sample(rng);
    (0..char_count)
        .map(|_| CHARS[distr_chars.sample(rng)] as char)
        .collect()
}

fn perform_mangle(fragment: &str, mangler: Mangler, rng: &mut dyn RngCore) -> String {
    match mangler {
        Mangler::RandomUppercase => fragment
            .chars()
            .map(|ch| {
                let distr_cap = Lazy::new(|| Uniform::new(0, 3));
                if (*distr_cap).sample(rng) == 0 {
                    // This is safe; we don't have unicode chars.
                    ch.to_uppercase().next().unwrap()
                } else {
                    ch
                }
            })
            .collect(),
        Mangler::AllUppercase => fragment.to_uppercase(),
        Mangler::ReplaceSeps => fragment
            .chars()
            .map(|ch| {
                let distr_replace = Lazy::new(|| Uniform::new(0, 4));
                if ch == '-' && (*distr_replace).sample(rng) == 0 {
                    const SEPS: &[u8] = b"!_+$";
                    let distr_seps = Lazy::new(|| Uniform::new(0, SEPS.len()));
                    SEPS[(*distr_seps).sample(rng)] as char
                } else {
                    ch
                }
            })
            .collect(),
        Mangler::NoOp => fragment.to_string(),
    }
}

fn get_mangler(rng: &mut dyn RngCore) -> Mangler {
    let distr_one_fourth = Lazy::new(|| Uniform::new(0, 12));
    match (*distr_one_fourth).sample(rng) {
        // 1/4 probability of selecting a mangler
        0 => Mangler::AllUppercase,
        1 => Mangler::RandomUppercase,
        2 => Mangler::ReplaceSeps,
        _ => Mangler::NoOp,
    }
}

fn mangle_fragment(fragment: &str, rng: &mut dyn RngCore) -> String {
    // Select mangling function
    let mangler = get_mangler(rng);
    let new = perform_mangle(fragment, mangler, rng);

    if rng.gen() && mangler != Mangler::NoOp {
        if mangler == Mangler::AllUppercase || mangler == Mangler::RandomUppercase {
            // Don't repeat a case mangling
            return perform_mangle(&new, Mangler::ReplaceSeps, rng);
        } else if mangler == Mangler::ReplaceSeps {
            let mangler = if rng.gen() {
                Mangler::AllUppercase
            } else {
                Mangler::RandomUppercase
            };
            return perform_mangle(&new, mangler, rng);
        }
    }

    new
}

pub(crate) fn shady_filename(rng: &mut dyn RngCore) -> String {
    arr!(const SEPS: [&str; _] = ["-", "!", "_", "+", "~"]);

    // These never change, so no point in regenerating them each time
    let distr_seps = Lazy::new(|| Uniform::new(0, SEPS.len()));
    let distr_nsfw = Lazy::new(|| Uniform::new(0, NSFW.len()));
    let distr_ext = Lazy::new(|| Uniform::new(0, EXT.len()));
    let distr_count = Lazy::new(|| Uniform::new_inclusive(6, 10));

    let hash = generate_hash(rng);

    /* We multiply by 2 so we can put on the separators and suffix
     * The total number of separators plus the suffix works out to be double the nsfw_count.
     * This means the hash_pos must be doubled, too, to be in the right spot.
     */
    let nsfw_count = distr_count.sample(rng) * 2;
    let hash_pos = rng.gen_range(0..nsfw_count) * 2;

    let mut seen_set = HashSet::new();
    (0..nsfw_count)
        .map(|i| {
            if (i & 1) == 1 {
                // This is odd. Do we tack on the suffix or a separator?
                if i == nsfw_count - 1 {
                    EXT[(*distr_ext).sample(rng)].to_string()
                } else {
                    // This position will always be odd, since nsfw_count * 2 is always even.
                    // NB: the range is [0..nsfw_count * 2)
                    //
                    SEPS[(*distr_seps).sample(rng)].to_string()
                }
            } else if i == hash_pos {
                hash.clone()
            } else {
                // Loop until we get a unique NSFW fragment
                loop {
                    let pos = (*distr_nsfw).sample(rng);
                    if seen_set.contains(&pos) {
                        continue;
                    }
                    seen_set.insert(pos);
                    return mangle_fragment(NSFW[pos], rng);
                }
            }
        })
        .collect()
}

arr!(const NSFW: [&str; _] = [
    "0percentartificial",
    "0percentrisk",
    "1$-iphone",
    "100percentlegal",
    "100percentnatural",
    "1man1jar",
    "2girls1cup",
    "2guys1horse",
    "3girlsfingerpaint",
    "3guys1hammer",
    "419-scam",
    "420",
    "500$-cashprize",
    "69",
    "7-11-robbery",
    "800-dollars-4u",
    "9-11-jumper",
    "9-11-video",
    "911-call",
    "abuse",
    "adblock-bypass",
    "admin",
    "ads",
    "advert",
    "affair",
    "al-qaeda",
    "al-qaeda-signup",
    "alien-abduction",
    "all-natural",
    "ambien",
    "america",
    "anal",
    "anal-penetration",
    "analsex",
    "anarchy",
    "ancient-cure",
    "ancient-diet-pills",
    "anti-aging-pills",
    "anti-e-pills",
    "anti-estrogen-pills",
    "anti-t-pills",
    "anti-testosterone-pills",
    "antifa-kills-maga",
    "antifamurder",
    "antivirus",
    "apple-giveaway",
    "arpa",
    "ass",
    "ass-beating",
    "ass2ass",
    "ass2mouth",
    "assault",
    "assfucking",
    "audio",
    "babes",
    "back-orifice",
    "backdoor",
    "bad-mixtape",
    "badonkadonk",
    "bang",
    "bang-women",
    "banktransfer",
    "barely-legal",
    "bargains",
    "basic",
    "bbw",
    "bdsm",
    "beatdown",
    "beatingwomen",
    "beheading",
    "betting",
    "bigbang",
    "bigcashprize",
    "bigcocks",
    "bigmilf",
    "bigwillie",
    "bigwomen",
    "billionaire",
    "bitcoin-2x",
    "bitcoin-billionaire",
    "bitcoin-cash-paydirt",
    "bitcoin-miner",
    "bitcoin-multiplier",
    "blackmaildox",
    "blood",
    "bloody-murder",
    "bodies",
    "body",
    "bodybuilders",
    "bomb",
    "bombing",
    "bondage",
    "bot",
    "boyfriendcamera",
    "boyfriendphone",
    "boyfriendtracker",
    "bribe-your-boss-legally",
    "build-muscle",
    "bupropion",
    "butt",
    "buttsex",
    "bypass",
    "calcium",
    "cash",
    "cashmoney",
    "casino",
    "casino-loosest-slots",
    "cat-torture",
    "celebaddresses",
    "celebphonenumbers",
    "celebsextape",
    "chat",
    "chatwithbabes",
    "cheap",
    "cheap-guns-ammo",
    "cheapcialis",
    "cheapdrugs",
    "cheappills",
    "cheapviagra",
    "cheat",
    "cheat-at-casino-legally",
    "cheating",
    "chop",
    "christian",
    "christian-evangelism",
    "christian-murder",
    "chromium-supplement",
    "cialis",
    "classified",
    "classified-doxxx",
    "click",
    "click-here",
    "clickjack",
    "clone-phone",
    "clone-simcard",
    "clownpenis",
    "cobalt-supplement",
    "cocaine",
    "cock",
    "cockfights",
    "coin",
    "coin-multiplier",
    "conspiracy",
    "cookie",
    "cookiestealer",
    "coupon",
    "cowgirl",
    "crack",
    "craigslist-blowjob",
    "craigslist-hookup",
    "creditcard",
    "creditcard-numbers",
    "crime-tips",
    "crypto",
    "cummy",
    "cure",
    "cure-anything",
    "cyber",
    "cyberattack",
    "cyberstalk",
    "daesh",
    "daeshmeetup",
    "daeshrecruitment",
    "daeshsignup",
    "darkweb",
    "date-hot-babes",
    "date-hot-chix",
    "date-hot-guys",
    "date-hot-trans-babes",
    "date-hot-trans-chix",
    "date-hot-trans-guys",
    "dating4oldppl",
    "dead-animals",
    "dead-people",
    "deals",
    "death",
    "declassified",
    "declassified-dox",
    "deepfake",
    "deepweb",
    "deepweb-drugs",
    "deepweb-guns",
    "deploy",
    "detector",
    "diaperkink",
    "diazepam",
    "dick",
    "dickenlargement",
    "diet",
    "diet-supplement",
    "digital",
    "digitalcurrency",
    "digitalpharmacy",
    "dildo",
    "dns",
    "doctor",
    "doctorrecommended",
    "dog-sex",
    "dog-torture",
    "dollar",
    "dollarforex",
    "domesticabuse",
    "donate",
    "donkey-cock",
    "donkey-show",
    "dothisbytomorrow",
    "dothisnow",
    "doxxing",
    "doxxx",
    "drivebyshooting",
    "drugs",
    "dungeon",
    "earn-ur-degree-online",
    "easymen",
    "easymoney",
    "easywomen",
    "echinacea",
    "effexor",
    "electionfraud",
    "email",
    "emailscam",
    "endless-health",
    "endless-money",
    "enhancement",
    "enter-2-win",
    "escort",
    "estradiol",
    "estrogen",
    "etherium",
    "etherium-multiplier",
    "euro",
    "euro-forex",
    "evangelical",
    "evidence",
    "exclusive-sextape",
    "exe",
    "execute",
    "extra",
    "fake",
    "fakelogin",
    "famine",
    "fap",
    "fappening",
    "fast",
    "fast-weightloss-diet",
    "fastremedy",
    "fastweightloss",
    "fight-aging",
    "finalmoments",
    "finalopportunity",
    "finalsolution",
    "finder",
    "fingering",
    "fisting",
    "flash",
    "flightpoints",
    "footageofdeath",
    "footfetish",
    "footporn",
    "forex",
    "forex-nobearmarket",
    "forexinterbank",
    "fraud",
    "freakout",
    "free",
    "freeandroid",
    "freeinternet",
    "freeiphone",
    "freemeds",
    "freephone",
    "freepills",
    "freeporn",
    "freeshows",
    "freetv",
    "freevirusremoval",
    "freewebcams",
    "french",
    "frottage",
    "fuck",
    "gangbang",
    "gay",
    "gay-sex",
    "german",
    "german-scat-porn",
    "getagirl",
    "getjacked",
    "getlaid",
    "getlaidtonite",
    "getrichovernight",
    "getrichquick",
    "getting-ucked",
    "ghetto",
    "ginger",
    "girl",
    "girlcock",
    "girldick",
    "girlfriend",
    "girlfriendcamera",
    "girlfriendphone",
    "girlfriendtracker",
    "giveaway",
    "gmail",
    "goatse",
    "gonesexual",
    "gonewild",
    "gonewrong",
    "google",
    "gore",
    "governmentdocuments",
    "governmentdox",
    "gps",
    "gpslocation",
    "gpstrack",
    "graphicimages",
    "grindr",
    "gunfight",
    "guns",
    "hacker",
    "hateminorities",
    "headshot",
    "hedies",
    "hefuxher",
    "helicoptercrash",
    "herbal",
    "herbalremedy",
    "heroin",
    "hidden",
    "hijack",
    "hijacker",
    "hitler",
    "hitler-sexfilm",
    "holisticmedicine",
    "homeless-man-murder",
    "homeless-woman-murder",
    "homelessdeath",
    "homeopathic",
    "hood-shooting",
    "horny-goat-weed",
    "horny-teens",
    "horny-women",
    "horse-sex",
    "hotbabes",
    "hotgoats",
    "hotwomen",
    "hotmail",
    "how2win",
    "how2winatcasino",
    "hugecashprize",
    "hugecocks",
    "hypnosis",
    "i-was-probed",
    "ied",
    "illegal",
    "illegal-drugs",
    "illegal-guns-4-sale",
    "illegal-porno",
    "iloveu",
    "imake2000aweekathome",
    "impersonate",
    "incest",
    "incest-daughter-father",
    "incest-daughter-mother",
    "incest-mother-son",
    "incest-father-son",
    "increase-ur-e",
    "increase-ur-t",
    "india",
    "install",
    "internet",
    "interview",
    "intifada",
    "invis",
    "ip-finder",
    "ip-hijacker",
    "ip-stealer",
    "iron",
    "irs",
    "isis",
    "isisrecruiter",
    "isistrainingcamp",
    "islam",
    "islam-murder",
    "israel",
    "iwasabductedbyaliens",
    "jackedoff",
    "jacking",
    "jackingit",
    "jackingoff",
    "jackpot",
    "jackpot-lottry-winner",
    "jailbait",
    "jailbeatdown",
    "jailbreak",
    "jailhouse-beatdown",
    "jailhouse-murder",
    "jailhouse-stabbing",
    "jailmurder",
    "jailstabbing",
    "japan",
    "japanese",
    "japanese-tentacle-porn",
    "jar-inserted",
    "jar-jar-porn",
    "java",
    "javascript",
    "javascript-exploit",
    "jelqing",
    "jew-nwo",
    "jewish-conspiracy",
    "jewishbanks",
    "jihad",
    "jizz",
    "jizz-fountain",
    "join-an-orgy",
    "join-now",
    "join-our-cult",
    "join-our-religion",
    "join-us",
    "joinisis",
    "journalist",
    "k9",
    "keygen",
    "keylog",
    "keylogger",
    "kill",
    "killallimmigrants",
    "killgays",
    "killing",
    "killwomen",
    "king",
    "kingscandal",
    "kinky",
    "kitty",
    "knifefight",
    "krack",
    "krazy-deals",
    "krazy-good-deal",
    "launch",
    "leak",
    "leaked-documents",
    "leaked-dox",
    "legal",
    "legend-tits",
    "legendary-growth",
    "legendjackpot",
    "lemonparty",
    "lesbian",
    "lesbiansfuck",
    "lesbo",
    "levitra",
    "lexapro",
    "lezbo",
    "linux",
    "local",
    "localmen",
    "localwomen",
    "locator",
    "loli",
    "lolicon",
    "lonelywomen",
    "looseslots",
    "loosesluts",
    "lorazepam",
    "lotto-winner",
    "lsd",
    "m4m",
    "m4t",
    "m4w",
    "macos",
    "maga",
    "magic",
    "magic-cure",
    "magicmushrooms",
    "magicweightloss",
    "makehercum",
    "makemoneyathome",
    "makemoneydoingnothing",
    "makemoneyfast",
    "maleenhancement",
    "malicious",
    "malware",
    "manybabes",
    "marijuana",
    "mature",
    "mdma",
    "medical",
    "medical-magic-mushrooms",
    "medical-mmj",
    "medicalmushrooms",
    "meds",
    "meds4cheap",
    "medsfromcanada",
    "medsfromchina",
    "medsfromeurope",
    "medsfromvanuatu",
    "mega",
    "megajackpot",
    "megatits",
    "mein-kampf",
    "mercenary",
    "microsoft-giveaway",
    "mike-pence",
    "mike-pence-gay",
    "mike-pence-naked",
    "milf",
    "milf-tits",
    "millionaire",
    "mine-coins-for-free",
    "mom-daughter-fuck",
    "mom-has-sex-with-son",
    "mommy-milkers",
    "monster-erection",
    "morecash",
    "moreincome",
    "moremoney",
    "morewins",
    "msm-supplement",
    "multivitamin",
    "mushrooms",
    "muslim",
    "muslim-murders-christian",
    "my-tits-are-legend",
    "naked",
    "nakedcelebs",
    "nazi",
    "nazi-beatdown",
    "new",
    "newcure",
    "newdrugs",
    "newincome",
    "newremedy",
    "newworldorder",
    "nft",
    "nigeria-bank-transfer",
    "no-risk",
    "nsfw",
    "nudes",
    "nwo",
    "old-ladies",
    "oldmangangbang",
    "oldmen",
    "oldremedy",
    "online-horse-race",
    "onlinebetting",
    "onlinepharma",
    "onlinepharmacy",
    "only10dollars",
    "orangutansex",
    "organ",
    "organ-selling",
    "overnight",
    "overnightcure",
    "overnightgrowth",
    "overnightwealth",
    "overnightweightloss",
    "overnitebillionaire",
    "overnitemillionaire",
    "overnitesuccess",
    "overnitetrillionaire",
    "paranomal",
    "password",
    "penetration",
    "penisenlargement",
    "petitmilf",
    "pewdiepie-sextape",
    "pharma",
    "pharmacanada",
    "pharmachina",
    "pharmacy",
    "pharmaeuro",
    "pharmavanuatu",
    "phishing",
    "phone",
    "phonenumbers",
    "phosphorous-supplements",
    "physical-removal",
    "pickup",
    "pickup-girls",
    "pigsex",
    "pills",
    "pills4cheap",
    "pimp",
    "pipebomb",
    "piratedmovies",
    "piratedmusic",
    "piratedpodcasts",
    "piratedshows",
    "pizzagate",
    "poker",
    "pokerrealmoney",
    "policebodycam",
    "poop",
    "popunder",
    "popup",
    "porn",
    "prince",
    "prince-scandal",
    "princess",
    "princess-scandal",
    "probe",
    "probing",
    "protein",
    "proteinpowder",
    "prozac",
    "psilocybin",
    "psilocybin-online",
    "public",
    "publicsex",
    "pussy",
    "pussyfuck",
    "putin",
    "putin-naked",
    "putinsdick",
    "pwn",
    "qanon",
    "qanonreveal",
    "queen",
    "queen-nudes",
    "queenscandal",
    "quickie",
    "quicklygetrich",
    "quiturjob",
    "racism-website",
    "racist",
    "racket",
    "rapid-growth",
    "rapid-weightloss",
    "ratsex",
    "read",
    "real",
    "realcatsex",
    "realdeath",
    "realdogsex",
    "realdonkeyshow",
    "reallyhornygirls",
    "remedy",
    "remote",
    "remoteviewing",
    "removevirus",
    "reverse",
    "rich",
    "richovernight",
    "rickroll",
    "ripoff",
    "rippedfast",
    "risperidol",
    "root",
    "rootkit",
    "ropebondage",
    "ropeporn",
    "russia",
    "russian",
    "russian-bots",
    "russian-brides",
    "scam",
    "scandal",
    "scat",
    "scat-porn",
    "school-shooting",
    "scissoring",
    "secret",
    "secret-plans",
    "secretary",
    "see-me-naked",
    "seeherwebcam",
    "seemypussy",
    "seemytits",
    "sell-your-organs",
    "seroquel",
    "sex",
    "sexoffender",
    "sext",
    "sextape",
    "sexting",
    "sextwithgrannies",
    "sexwithcats",
    "sexwithdogs",
    "sexwithgerbils",
    "sexy",
    "sexyladies",
    "sexywomen",
    "shartporn",
    "she-will-never-know",
    "shedies",
    "shefuxhim",
    "shemale",
    "shes-barely-legal",
    "sheswaiting4u",
    "shit",
    "shitfountain",
    "shitfucking",
    "shocking",
    "shocksite",
    "shooting",
    "shoplifting",
    "shota",
    "shotacon",
    "sim-clone",
    "skinned-alive",
    "skinned-cats",
    "slutcams",
    "sluts",
    "smallcocks",
    "sms",
    "snuff-films",
    "social-security",
    "sound",
    "sourcecode",
    "sourcecode-leak",
    "spam",
    "spy",
    "spyonurboyfriend",
    "spyonurgirlfriend",
    "spyonurhusband",
    "spyonurwife",
    "spyware",
    "stalkher",
    "steal",
    "stjohnswort",
    "stoned",
    "stoned-for-adultery",
    "stud",
    "stuxnet",
    "subwaydeath",
    "supplements",
    "supplementscheap",
    "suppository",
    "sweepstakes",
    "swissbankaccount",
    "swisslottowinner",
    "swissporn",
    "t4m",
    "t4t",
    "t4w",
    "takeover",
    "taliban-interview",
    "taliban-meetup",
    "taliban-recruiter",
    "teen",
    "teen-barely-legal",
    "telegram",
    "televangelist",
    "terrorist",
    "testosterone",
    "testosterone-supplement",
    "the-donald",
    "the-truth-about-jews",
    "thetruth",
    "they-hurt-her",
    "theycantstopyou",
    "theyhatethis",
    "threesomes",
    "threesomes-near-u",
    "tighten-my-pussy",
    "tokens",
    "toohot4tv",
    "tool",
    "toosexy",
    "toosexy4youtube",
    "tor",
    "torrent",
    "torrent-anything",
    "tracker",
    "trackmyex",
    "trackmywife",
    "trans",
    "trans-agenda",
    "trans-doctor",
    "trans-porn",
    "trillionaire",
    "trojan",
    "turkey-porn",
    "twitter-blowjob",
    "un-nwo-conspiracy",
    "underground-death",
    "unlocker",
    "ur-hubby-is-cumming",
    "ur-jackpot-awaits",
    "ur-wife-is-cumming",
    "usa",
    "vagina",
    "vaginal-rejeuvenation",
    "vanadium-supplement",
    "viagra",
    "video",
    "virus",
    "vitamin-b12",
    "vitamin-b6",
    "vitamin-c",
    "vitamin-d",
    "vitamin-e",
    "vitamins",
    "vpn",
    "vuln",
    "vulns",
    "w4m",
    "w4t",
    "w4w",
    "warcrimes",
    "warez",
    "warphotos",
    "watch",
    "watch-her-die",
    "watch-her-get-fukd",
    "watch-her-webcam",
    "watch-him-die",
    "watchmovies4free",
    "watchtv4free",
    "web",
    "weed",
    "weightloss",
    "wet",
    "wetfartporn",
    "wetpussy",
    "wfh",
    "what-hes-doing",
    "what-shes-doing",
    "whattheydontwantu2know",
    "whitepower",
    "whos-my-husband-txting",
    "whos-my-wife-txting",
    "wifepussy",
    "win",
    "winatblackjack",
    "winatpoker",
    "winbig",
    "windows",
    "winning",
    "winning-lotto-numbers",
    "woman-gets-stoned",
    "womanbeaten",
    "women",
    "workathome",
    "worldstar",
    "worldstarfight",
    "worm",
    "wow",
    "xtc",
    "xxx",
    "xxx-pussy",
    "xxx-tits",
    "xxxtra",
    "yahoo",
    "yen",
    "yenforex",
    "you-won",
    "youre-a-winner",
    "yourip",
    "yourssn",
    "youtube-download",
    "zinc-supplement",
    "zoo",
    "zoom",
    "zooporn",

]);

arr!(const EXT: [&str; _] = [
    ".app", ".avi", ".bas", ".bat", ".csv", ".divx", ".dll", ".doc", ".docx", ".exe", ".flv", ".gif", ".htm",
    ".html", ".hxt", ".ini", ".jar", ".js", ".jpeg", ".jpg", ".m1v", ".m4a", ".mid", ".midi", ".mkv", ".mod",
    ".mov", ".movie", ".mpa", ".mpe", ".mpeg", ".mpg", ".mp3", ".mp4", ".msi", ".p7r", ".pdf", ".png", ".ppt",
    ".pptx", ".rar", ".sgml", ".snd", ".swf", ".tiff", ".txt", ".webm", ".webp", ".vbs", ".xaf", ".xhtml",
    ".xls", ".xlsx", ".xml", ".zip",
]);
