//! `SeaORM` Entity. Generated by sea-orm-codegen 1.0.0-rc.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub username: String,
    pub password_hash: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cidr_ban::Entity")]
    CidrBan,
    #[sea_orm(has_many = "super::url_filter::Entity")]
    UrlFilter,
}

impl Related<super::cidr_ban::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CidrBan.def()
    }
}

impl Related<super::url_filter::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UrlFilter.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
